# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(default='numero_doc', max_length=50)),
                ('nombre', models.CharField(default='nombre', max_length=150)),
                ('apellido', models.CharField(default='apellido', max_length=150)),
                ('genero', models.CharField(default='genero', max_length=150)),
                ('edad', models.CharField(default='edad', max_length=150)),
                ('foto', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nombre', models.CharField(default='facultad', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEgresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(default='ciudad', max_length=150)),
                ('estado_civil', models.CharField(default='estado_civil', max_length=150)),
                ('estrato', models.CharField(default='estrato', max_length=150)),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modalidad', models.CharField(default='modalidad', max_length=150)),
                ('fecha_inic', models.CharField(default='fecha-inic', max_length=150)),
                ('fecha_fin', models.CharField(default='fecha-fin', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(default='programa', max_length=150)),
                ('id_facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pago', models.CharField(default='tipo-pago', max_length=150)),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Egresado')),
            ],
        ),
        migrations.AddField(
            model_name='modalidad',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Programa'),
        ),
    ]
