# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20171125_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_pago',
            new_name='TipoPago',
        ),
        migrations.RenameField(
            model_name='facultad',
            old_name='nombre_nombre',
            new_name='nombre_facultad',
        ),
    ]
