# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_remove_egresado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumEgresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('edad', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'album_egresado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumFacultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'album_facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumInfoegresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=150)),
                ('estado_civil', models.CharField(max_length=100)),
                ('estrato', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'album_infoegresado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumModalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modalidad', models.CharField(max_length=150)),
                ('fecha_inic', models.CharField(max_length=150)),
                ('fecha_fin', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'album_modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'album_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumTipopago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pago', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'album_tipopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_egresado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=50, null=True)),
                ('estrato', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'egresado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='infoegresado',
            name='id_estudiante',
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modalidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipopago',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='InfoEgresado',
        ),
    ]
