# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20171126_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_egresado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=50, null=True)),
                ('estrato', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'egresado',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='facultad',
            table='facultad',
        ),
        migrations.AlterModelTable(
            name='modalidad',
            table='modalidad',
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
        migrations.AlterModelTable(
            name='tipopago',
            table='tipo_pago',
        ),
    ]
